pipeline:
  install-deps:
    image: microlayers/golang-with-extras:1.11.2-stretch
    pull: true
    commands:
      - go mod download
    volumes:
      - gopath:/go

  run-linter:
    group: tests
    image: microlayers/golang-with-extras:1.11.2-stretch
    environment:
      - "GOBIN=/root/go/bin"
      - "LINTER_VERSION=v2.0.11"
    commands:
      - export PATH="$GOBIN:$PATH"
      - curl -L https://git.io/vp6lP | bash -s -- -b $GOBIN
      # https://github.com/golang/go/issues/24661
      - gometalinter ./... -Dgotype -Dgotypex -Dmaligned -Dunconvert -Dinterfacer -Dmegacheck -Dstructcheck -Dvarcheck
    volumes:
      - gopath:/root/go

  run-tests:
    group: tests
    image: microlayers/golang-with-extras:1.11.2-stretch
    commands:
      - ./test.sh
    volumes:
      - gopath:/root/go

  upload-coverage:
    group: post-tests
    image: microlayers/golang-with-extras:1.11.2-stretch
    secrets:
      - codecov_token
    commands:
      - bash -c "bash <(curl -s https://codecov.io/bash)"
    volumes:
      - gopath:/root/go

  run-build:
    group: post-tests
    image: microlayers/golang-with-extras:1.11.2-stretch
    commands:
      - go build
    volumes:
      - gopath:/root/go

images:
  gopath:
