pipeline:
  install-deps:
    image: microlayers/golang-with-extras:1.11.2-stretch
    pull: true
    commands:
      - go mod download
    volumes:
      - gopath:/go
  run-linter:
    image: microlayers/golang-with-extras:1.11.2-stretch
    commands:
      - ./lint.sh
    volumes:
      - gopath:/root/go
  run-tests:
    image: microlayers/golang-with-extras:1.11.2-stretch
    commands:
      - ./test.sh
    volumes:
      - gopath:/root/go
  run-build:
    image: microlayers/golang-with-extras:1.11.2-stretch
    commands:
      - go build
  upload-coverage:
    image: microlayers/golang-with-extras:1.11.2-stretch
    secrets:
      - codecov_token
    commands:
      - bash -c "bash <(curl -s https://codecov.io/bash)"

images:
  gopath:
