server:
  module: mymodule.so
  listen:
    unix:
      enabled: false
      protocol: whatever
      socket: /dir/my.sock
    tcp:
      enabled: true
      port: 62546
      protocol: vdm
    http:
      enabled: false
      port: 0
      protocol: ""
