server:
  module: mymodule.so
  listen:
    unix:
      enabled: false
      protocol: whatever
      socket: /dir/my.sock
    tcp:
      enabled: true
      protocol: vdm
      port: 62546
    http:
      enabled: false
      protocol: ""
      port: 0
